# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: creative_seq.proto

require 'google/protobuf'

require 'creative_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("creative_seq.proto", :syntax => :proto2) do
    add_message "FYBER.userconfiguration.CreativeSeq" do
      repeated :creative, :message, 1, "FYBER.userconfiguration.Creative"
    end
  end
end

module FYBER
  module Userconfiguration
    CreativeSeq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.CreativeSeq").msgclass
  end
end
