# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: placement_seq.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("placement_seq.proto", syntax: :proto2) do
    add_message "FYBER.userconfiguration.PlacementSeq" do
      repeated :placement, :message, 1, "FYBER.userconfiguration.Placement"
    end
  end
end

module FYBER
  module Userconfiguration
    PlacementSeq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FYBER.userconfiguration.PlacementSeq").msgclass
  end
end
